const cfg = window.R2V_QUALITY_CONFIG || {};
const db = window.supabase?.createClient?.(cfg.supabaseUrl, cfg.supabaseKey);
const $ = (id) => document.getElementById(id);
const state = { events: [], feedback: [], appeals: [], roles: [], imports: [], adminAudit: [], cases: [], qualityRounds: [], acceptanceRounds: [], pendingDelete: null, actor: localStorage.getItem('r2v_quality_actor') || '' };
const inspectorFallback = new Set(['于蕊','唐子旖','连晓燕','乔一佳','王雨鲲','相伟达']);
const titles = { overview:'质量总览', people:'人员质量', cases:'Case 明细', appeals:'申诉中心', imports:'数据上传' };

function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pct(n,d){return d ? `${(n/d*100).toFixed(1)}%` : '—';}
function day(v){if(!v)return ''; const d=new Date(v); return Number.isNaN(d.valueOf())?String(v).slice(0,10):d.toISOString().slice(0,10);}
function dateTime(v){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.valueOf()))return String(v).replace('T',' ').slice(0,16);return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d).replaceAll('/','-');}
function normalizeName(v=''){const s=String(v).trim(); return s.replace(/^[a-zA-Z][a-zA-Z0-9._-]*(?=[\u4e00-\u9fff])/,'').trim();}
function hashText(s){let h=2166136261; for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
function showStatus(text,error=false){const el=$('statusBar');el.textContent=text;el.className=`status-bar${error?' error':''}`;clearTimeout(showStatus.t);showStatus.t=setTimeout(()=>el.classList.add('hidden'),6500);}
function chunk(arr,n=500){const out=[];for(let i=0;i<arr.length;i+=n)out.push(arr.slice(i,i+n));return out;}
function dedupeBy(arr,key){const out=new Map();for(const item of arr){const id=item[key];if(!out.has(id)){out.set(id,item);continue;}const prev=out.get(id),evidence=[...new Set([...(prev.evidence||[]),...(item.evidence||[])])];out.set(id,{...prev,...item,...(prev.evidence||item.evidence?{evidence}:{})});}return [...out.values()];}
function groupBy(arr,keyFn){return arr.reduce((out,item)=>{const key=keyFn(item);(out[key]??=[]).push(item);return out;},{});}
function isInspector(name){const role=state.roles.find(r=>r.person_name===name)?.role;return role==='inspector'||(!role&&inspectorFallback.has(name));}
function periodBounds(){const v=$('periodSelect')?.value||'all',today=day(new Date());if(v==='all')return {start:'',end:'',label:'全部累计'};if(v==='custom'){const start=$('startDate')?.value||'',end=$('endDate')?.value||'';return {start,end,label:start||end?`${start||'最早'} 至 ${end||'最新'}`:'请选择日期'};}const d=new Date(`${today}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-Number(v)+1);return {start:day(d),end:today,label:v==='1'?today:`${day(d)} 至 ${today}`};}
function inPeriod(date){const key=day(date),{start,end}=periodBounds();if(!key)return false;return (!start||key>=start)&&(!end||key<=end);}
function syncPeriodDates(){const select=$('periodSelect'),today=day(new Date()),todayOption=select.querySelector('option[value="1"]');todayOption.textContent=`单日（今天：${today}）`;const v=select.value;if(v==='custom')return;if(v==='all'){$('startDate').value='';$('endDate').value='';return;}const bounds=periodBounds();$('startDate').value=bounds.start;$('endDate').value=bounds.end;}
function setPeriodPreset(){syncPeriodDates();renderAll();}
function useCustomDates(){if($('startDate').value||$('endDate').value)$('periodSelect').value='custom';}
function applyPeriod(){const start=$('startDate').value,end=$('endDate').value;if(start&&end&&start>end)return showStatus('开始日不能晚于结束日。',true);renderAll();showStatus(`已按 ${periodBounds().label} 重新计算。`);}

async function ensureActor(){if(state.actor)return state.actor;const name=prompt('请输入你的姓名。上传、申诉和裁决会记录这个名字。','');if(!name?.trim())return '';state.actor=name.trim();localStorage.setItem('r2v_quality_actor',state.actor);renderIdentity();return state.actor;}
function renderIdentity(){$('identityBtn').textContent=state.actor||'设置姓名';}

async function loadAll(){
  if(!db){showStatus('云端配置未加载，请刷新页面。',true);return;}
  const tables=[['events','r2v_quality_events','event_time','event_key',200000],['feedback','r2v_quality_feedback','updated_at','feedback_key',100000],['appeals','r2v_quality_appeals','updated_at','id',50000],['roles','r2v_quality_staff_roles','person_name','person_name',10000],['imports','r2v_quality_imports','created_at','id',10000],['adminAudit','r2v_quality_admin_audit','created_at','id',10000]];
  try{
    showStatus('正在读取全部历史流水…');
    for(const [key,table,order,tie,max] of tables){const rows=[];for(let from=0;from<max;from+=1000){let query=db.from(table).select('*').order(order,{ascending:key==='roles'});if(tie!==order)query=query.order(tie,{ascending:true});const {data,error}=await query.range(from,Math.min(from+999,max-1));if(error)throw error;rows.push(...(data||[]));if(!data||data.length<1000)break;}state[key]=rows;}
    rebuild();renderAll();
  }catch(e){showStatus(`数据库尚未就绪：${e.message}。请先执行 supabase-schema.sql。`,true);}
}

function sortedEvents(tid){return state.events.filter(e=>e.tid===tid).sort((a,b)=>new Date(a.event_time)-new Date(b.event_time));}
function lastBefore(events,index,predicate){for(let i=index-1;i>=0;i--)if(predicate(events[i]))return events[i];return null;}
function originalAnnotator(events,index){for(let i=index-1;i>=0;i--){const e=events[i];if(e.event_name==='标注'&&e.operator_name&&!isInspector(normalizeName(e.operator_name)))return normalizeName(e.operator_name);}for(let i=index-1;i>=0;i--){const e=events[i];if(e.event_name==='标注'&&e.operator_name)return normalizeName(e.operator_name);}return '待匹配';}

function buildQualityRounds(){
  const groups=groupBy(state.events.filter(e=>e.channel==='quality'),e=>e.tid);const rounds=[];
  for(const [tid,events0] of Object.entries(groups)){const events=events0.sort((a,b)=>new Date(a.event_time)-new Date(b.event_time));let round=0;
    events.forEach((e,i)=>{if(!['质检通过','质检不通过','质检打回'].includes(e.event_name))return;if(e.event_name==='质检打回'&&lastBefore(events,i,x=>x.event_name==='验收打回')&&!lastBefore(events,i,x=>x.event_name==='标注'&&new Date(x.event_time)>new Date(lastBefore(events,i,y=>y.event_name==='验收打回')?.event_time||0)))return;round++;rounds.push({tid,round,event:e.event_name,date:e.event_time,annotator:originalAnnotator(events,i),inspector:normalizeName(e.operator_name)||'待匹配',reason:e.reject_reason||'',first:round===1,invalid:e.event_name==='质检不通过'});});
  }return rounds;
}

function buildAcceptanceRounds(){
  const groups=groupBy(state.events,e=>e.tid);const rounds=[];
  for(const [tid,events0] of Object.entries(groups)){const events=events0.sort((a,b)=>new Date(a.event_time)-new Date(b.event_time));const entries=events.map((e,i)=>e.event_name==='进入验收池'?i:-1).filter(i=>i>=0);
    entries.forEach((start,ri)=>{const end=entries[ri+1]??events.length;const decisions=[];for(let i=start;i<end;i++)if(['验收通过','验收不通过'].includes(events[i].event_name))decisions.push({e:events[i],i});if(!decisions.length)return;const final=decisions.at(-1);let qc=null;for(let i=final.i-1;i>=0;i--)if(events[i].event_name==='质检通过'&&events[i].operator_name){qc={e:events[i],i};break;}const ai=qc?.i??start;rounds.push({key:`${tid}:${ri+1}`,tid,round:ri+1,entryDate:events[start].event_time,resultDate:final.e.event_time,result:final.e.event_name==='验收通过'?'passed':'failed',reason:final.e.reject_reason||'',inspector:normalizeName(qc?.e.operator_name)||'待匹配',annotator:originalAnnotator(events,ai),events:events.slice(start,end)});});
  }return rounds;
}

function latestAppeal(feedbackKey){return state.appeals.filter(a=>a.feedback_key===feedbackKey).sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at))[0];}
function rebuild(){
  state.qualityRounds=buildQualityRounds();state.acceptanceRounds=buildAcceptanceRounds();const firstByTid=new Map(state.qualityRounds.filter(r=>r.first).map(r=>[r.tid,r]));
  const feedbackCases=state.feedback.map(f=>{const q=firstByTid.get(f.tid);const app=latestAppeal(f.feedback_key),invalid=q?.invalid===true;return {...f,kind:'quality',annotator:q?.annotator||'待匹配',responsible_inspector:q?.inspector||normalizeName(f.inspector_name)||'待匹配',case_date:q?.date||f.feedback_date,appeal:app,invalid,final_error:!invalid&&['P0','P1'].includes(f.severity)&&app?.status!=='approved'};});
  const known=new Set(feedbackCases.map(c=>c.tid));const synthetic=state.qualityRounds.filter(r=>r.first&&['质检不通过','质检打回'].includes(r.event)&&!known.has(r.tid)).map(r=>({feedback_key:`flow:${r.tid}:${r.round}`,tid:r.tid,feedback_date:day(r.date),source:'quality',severity:'待定级',issue_category:r.invalid?'双方拒绝（无效）':'流水打回',issue_detail:r.reason||(r.invalid?'标注和质检均拒绝，该Case不进入准确率分母':'质检明确打回，缺少线下定级'),inspector_name:r.inspector,evidence:[],kind:'quality',annotator:r.annotator,responsible_inspector:r.inspector,case_date:r.date,invalid:r.invalid,final_error:!r.invalid,appeal:null,synthetic:true}));
  const acceptance=state.acceptanceRounds.filter(r=>r.result==='failed').map(r=>({feedback_key:`acceptance:${r.key}`,tid:r.tid,feedback_date:day(r.resultDate),source:'acceptance',severity:'—',issue_category:'验收不通过',issue_detail:r.reason,inspector_name:r.inspector,evidence:[],kind:'acceptance',annotator:r.annotator,responsible_inspector:r.inspector,case_date:r.entryDate,final_error:true,appeal:null,round:r.round,events:r.events}));
  state.cases=[...feedbackCases,...synthetic,...acceptance];
}

function aggregate(){
  const qRounds=state.qualityRounds.filter(r=>r.first&&!r.invalid&&inPeriod(r.date));const qByTid=new Map(qRounds.map(r=>[r.tid,r]));const qCases=state.cases.filter(c=>c.kind==='quality'&&!c.invalid&&qByTid.has(c.tid));const aRounds=state.acceptanceRounds.filter(r=>inPeriod(r.entryDate));
  const people=new Map();const get=n=>{if(!people.has(n))people.set(n,{name:n,qTotal:0,p0:0,p1:0,p2:0,errors:new Set(),approved:0,aTotal:0,aFail:0});return people.get(n)};
  qRounds.forEach(r=>get(r.annotator).qTotal++);qCases.forEach(c=>{const p=get(c.annotator);if(c.severity==='P0')p.p0++;if(c.severity==='P1')p.p1++;if(c.severity==='P2')p.p2++;if(c.appeal?.status==='approved')p.approved++;if(c.final_error)p.errors.add(c.tid);});aRounds.forEach(r=>{const p=get(r.annotator);p.aTotal++;if(r.result==='failed')p.aFail++;});
  const inspectors=new Map();aRounds.forEach(r=>{const p=inspectors.get(r.inspector)||{name:r.inspector,total:0,fail:0};p.total++;if(r.result==='failed')p.fail++;inspectors.set(r.inspector,p)});
  return {qRounds,qCases,aRounds,people:[...people.values()].filter(p=>p.name!=='待匹配').sort((a,b)=>b.qTotal-a.qTotal),inspectors:[...inspectors.values()].filter(p=>p.name!=='待匹配').sort((a,b)=>b.total-a.total)};
}

function renderAll(){renderIdentity();renderOverview();renderDailyStats();renderDailyPeople();renderPeople();renderCases();renderAppeals();renderImports();}
function renderOverview(){const a=aggregate(),errors=new Set(a.qCases.filter(c=>c.final_error).map(c=>c.tid));$('mQcTotal').textContent=a.qRounds.length;$('mQcErrors').textContent=errors.size;$('mQcAccuracy').textContent=pct(a.qRounds.length-errors.size,a.qRounds.length);$('mAcceptanceTotal').textContent=a.aRounds.length;$('mInspectorAccuracy').textContent=pct(a.aRounds.filter(r=>r.result==='passed').length,a.aRounds.length);
  const pending=a.qCases.filter(c=>['P0','P1'].includes(c.severity)&&!c.appeal).length,appealing=a.qCases.filter(c=>c.appeal?.status==='submitted').length,ungraded=a.qCases.filter(c=>c.severity==='待定级').length,match=state.cases.filter(c=>c.annotator==='待匹配'||c.responsible_inspector==='待匹配').length;
  $('todoList').innerHTML=[['待确认或申诉',pending,'质检P0/P1'],['申诉待裁决',appealing,'裁决后自动回算'],['历史待定级',ungraded,'不影响P级分布'],['人员待匹配',match,'需要补角色或流水']].map(x=>`<div class="todo-row"><span class="todo-count">${x[1]}</span><div><strong>${x[0]}</strong><small>${x[2]}</small></div><button class="text-button" data-go="${x[0].includes('申诉')?'appeals':'cases'}">处理</button></div>`).join('');
  const sev=['P0','P1','P2'],counts=sev.map(s=>a.qCases.filter(c=>c.severity===s).length),max=Math.max(1,...counts);$('severityBars').innerHTML=sev.map((s,i)=>`<div class="bar-row"><strong>${s}</strong><div class="bar-track"><div class="bar-fill ${s.toLowerCase()}" style="width:${counts[i]/max*100}%"></div></div><span>${counts[i]}</span></div>`).join('');$('overviewPeople').innerHTML=peopleRows(a.people.slice(0,8),false);bindGo();}
function renderDailyStats(){const a=aggregate(),dates=new Set([...a.qRounds.map(r=>day(r.date)),...a.aRounds.map(r=>day(r.entryDate))]);const rows=[...dates].filter(Boolean).sort().reverse().map(date=>{const q=a.qRounds.filter(r=>day(r.date)===date),tids=new Set(q.map(r=>r.tid)),errors=new Set(a.qCases.filter(c=>c.final_error&&tids.has(c.tid)).map(c=>c.tid)),acc=a.aRounds.filter(r=>day(r.entryDate)===date),fails=acc.filter(r=>r.result==='failed').length;return {date,q:q.length,errors:errors.size,acc:acc.length,fails};});$('periodSummary').textContent=`当前范围：${periodBounds().label}。按生产日统计，区间数据为多天累计。`;$('dailyTable').innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.date)}</strong></td><td>${r.q}</td><td>${r.errors}</td><td class="rate">${pct(r.q-r.errors,r.q)}</td><td>${r.acc}</td><td>${r.fails}</td><td class="rate">${pct(r.acc-r.fails,r.acc)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty-cell">所选日期范围内暂无质检或验收数据。</td></tr>';}
function renderDailyPeople(){const a=aggregate(),groups=new Map();a.qRounds.forEach(r=>{const date=day(r.date),key=`${date}|${r.annotator}`;if(!groups.has(key))groups.set(key,{date,name:r.annotator,total:0,p0:0,p1:0,p2:0,errors:new Set(),approved:0,tids:new Set()});const g=groups.get(key);g.total++;g.tids.add(r.tid);});a.qCases.forEach(c=>{const date=day(c.case_date||c.feedback_date),g=groups.get(`${date}|${c.annotator}`);if(!g)return;if(c.severity==='P0')g.p0++;if(c.severity==='P1')g.p1++;if(c.severity==='P2')g.p2++;if(c.appeal?.status==='approved')g.approved++;if(c.final_error)g.errors.add(c.tid);});const rows=[...groups.values()].filter(g=>g.name!=='待匹配').sort((x,y)=>y.date.localeCompare(x.date)||x.name.localeCompare(y.name,'zh-CN'));$('dailyPeopleTable').innerHTML=rows.length?rows.map(g=>`<tr><td><strong>${esc(g.date)}</strong></td><td><strong>${esc(g.name)}</strong></td><td>${g.total}</td><td>${g.p0}</td><td>${g.p1}</td><td>${g.p2}</td><td>${g.errors.size}</td><td>${g.approved}</td><td class="rate">${pct(g.total-g.errors.size,g.total)}</td></tr>`).join(''):'<tr><td colspan="9" class="empty-cell">所选日期范围内暂无人员质检数据。</td></tr>';}
function peopleRows(rows,full=true){if(!rows.length)return `<tr><td colspan="${full?10:8}" class="empty-cell">上传流水和反馈表后，这里会自动出现人员结果。</td></tr>`;return rows.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${p.qTotal}</td><td>${p.p0}</td><td>${p.p1}</td><td>${p.p2}</td>${full?`<td>${p.errors.size}</td>`:`<td>${p.approved}</td>`}<td class="rate">${pct(p.qTotal-p.errors.size,p.qTotal)}</td>${full?`<td>${p.aTotal}</td><td>${p.aFail}</td>`:''}<td class="rate">${pct(p.aTotal-p.aFail,p.aTotal)}</td></tr>`).join('')}
function renderPeople(){const a=aggregate();$('peopleTable').innerHTML=peopleRows(a.people,true);$('inspectorsTable').innerHTML=a.inspectors.length?a.inspectors.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${p.total}</td><td>${p.total-p.fail}</td><td>${p.fail}</td><td class="rate">${pct(p.total-p.fail,p.total)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-cell">上传验收流水后生成质检人员验收准确率。</td></tr>'}

function severityBadge(s){const c=s==='P0'?'p0':s==='P1'?'p1':s==='P2'?'p2':'pending';return `<span class="badge ${c}">${esc(s||'待定级')}</span>`;}
function caseStatus(c){if(c.invalid)return '无效剔除';if(c.appeal)return appealStatus(c.appeal.status);return c.kind==='acceptance'?'拉齐':'待确认';}
function qualityReturned(c){if(c.kind!=='quality')return '—';return c.needs_change===true?'是':c.needs_change===false?'否':'未填写';}
function feedbackExcelRow(c){const n=Number(c.raw_row?.excelRow);return Number.isFinite(n)&&n>0?n:Number.MAX_SAFE_INTEGER;}
function feedbackOrder(a,b){const dateDiff=String(day(b.feedback_date)).localeCompare(String(day(a.feedback_date)));if(dateDiff)return dateDiff;const ar=feedbackExcelRow(a),br=feedbackExcelRow(b);if(ar!==br)return ar-br;return String(a.tid||'').localeCompare(String(b.tid||''));}
function caseFilterBase(){return state.cases.filter(c=>inPeriod(c.case_date||c.feedback_date));}
function setCaseFilterOptions(id,items,allLabel='全部'){const el=$(id);if(!el)return;const current=el.value||'all',unique=[...new Map(items.filter(x=>x?.value).map(x=>[x.value,x])).values()].sort((a,b)=>a.label.localeCompare(b.label,'zh-CN'));el.innerHTML=`<option value="all">${esc(allLabel)}</option>${unique.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}`;el.value=unique.some(x=>x.value===current)?current:'all';}
function populateCaseFilters(){const rows=caseFilterBase();setCaseFilterOptions('caseDateFilter',rows.map(c=>({value:day(c.feedback_date),label:day(c.feedback_date)||'无日期'})),'全部日期');setCaseFilterOptions('caseSourceFilter',rows.map(c=>({value:c.kind,label:c.kind==='quality'?'质检':'验收'})),'全部来源');setCaseFilterOptions('caseAnnotatorFilter',rows.map(c=>({value:c.annotator,label:c.annotator||'待匹配'})),'全部标注人');setCaseFilterOptions('caseInspectorFilter',rows.map(c=>({value:c.responsible_inspector,label:c.responsible_inspector||'待匹配'})),'全部质检人');setCaseFilterOptions('caseSeverityFilter',rows.map(c=>({value:c.kind==='quality'?c.severity:'—',label:c.kind==='quality'?(c.severity||'待定级'):'—'})),'全部等级');setCaseFilterOptions('caseReturnedFilter',rows.map(c=>({value:qualityReturned(c),label:qualityReturned(c)})),'全部打回状态');setCaseFilterOptions('caseCategoryFilter',rows.map(c=>({value:c.issue_category||'—',label:c.issue_category||'—'})),'全部类别');setCaseFilterOptions('caseStatusFilter',rows.map(c=>({value:caseStatus(c),label:caseStatus(c)})),'全部状态');}
function filteredCases(){const value=id=>$(id)?.value||'all',text=id=>($(id)?.value||'').trim().toLowerCase(),term=text('caseSearch'),tid=text('caseTidFilter'),detail=text('caseDetailFilter');let rows=caseFilterBase();const exact=[[value('caseDateFilter'),c=>day(c.feedback_date)],[value('caseSourceFilter'),c=>c.kind],[value('caseAnnotatorFilter'),c=>c.annotator],[value('caseInspectorFilter'),c=>c.responsible_inspector],[value('caseSeverityFilter'),c=>c.kind==='quality'?c.severity:'—'],[value('caseReturnedFilter'),c=>qualityReturned(c)],[value('caseCategoryFilter'),c=>c.issue_category||'—'],[value('caseStatusFilter'),c=>caseStatus(c)]];for(const [selected,getter] of exact)if(selected!=='all')rows=rows.filter(c=>getter(c)===selected);if(tid)rows=rows.filter(c=>String(c.tid||'').toLowerCase().includes(tid));if(detail)rows=rows.filter(c=>String(c.issue_detail||'').toLowerCase().includes(detail));if(term)rows=rows.filter(c=>[c.tid,c.annotator,c.responsible_inspector,c.issue_category,c.issue_detail,caseStatus(c)].some(v=>String(v||'').toLowerCase().includes(term)));return rows.sort(feedbackOrder);}
function renderCases(){populateCaseFilters();const rows=filteredCases(),baseCount=caseFilterBase().length;$('caseFilterCount').textContent=`当前显示 ${rows.length} 条，共 ${baseCount} 条；质检反馈 Case 按原 Excel 行号排列，导出结果与筛选一致`;$('casesTable').innerHTML=rows.length?rows.slice(0,1000).map(c=>`<tr><td>${esc(day(c.feedback_date))}</td><td><span class="badge ${c.kind}">${c.kind==='quality'?'质检':'验收'}</span></td><td>${esc(c.tid)}</td><td>${esc(c.annotator)}</td><td>${esc(c.responsible_inspector)}</td><td>${c.kind==='quality'?severityBadge(c.severity):'—'}</td><td>${esc(qualityReturned(c))}</td><td>${esc(c.issue_category||'—')}</td><td title="${esc(c.issue_detail)}">${esc((c.issue_detail||'').slice(0,38))}</td><td>${caseStatus(c)}</td><td><button class="text-button case-open" data-key="${esc(c.feedback_key)}">详情</button></td></tr>`).join(''):'<tr class="filter-empty"><td colspan="11" class="empty-cell">没有符合当前组合筛选条件的 Case，可点击“清除筛选”恢复。</td></tr>';document.querySelectorAll('.case-open').forEach(b=>b.onclick=()=>openCase(b.dataset.key));}
function clearCaseFilters(){['caseDateFilter','caseSourceFilter','caseAnnotatorFilter','caseInspectorFilter','caseSeverityFilter','caseReturnedFilter','caseCategoryFilter','caseStatusFilter'].forEach(id=>{if($(id))$(id).value='all'});['caseSearch','caseTidFilter','caseDetailFilter'].forEach(id=>{if($(id))$(id).value=''});renderCases();}
function exportCases(){const rows=filteredCases();if(!rows.length)return showStatus('当前筛选条件下没有可导出的Case。',true);const data=rows.map(c=>({'统计日期':day(c.case_date||c.feedback_date),'反馈日期':day(c.feedback_date),'来源':c.kind==='quality'?'质检':'验收','TID':c.tid,'标注人':c.annotator,'质检人':c.responsible_inspector,'错误等级':c.kind==='quality'?c.severity:'—','质检是否打回':qualityReturned(c),'问题类别':c.issue_category||'','问题说明':c.issue_detail||'','统计状态':caseStatus(c),'是否计入准确率':c.invalid?'否（无效）':c.final_error?'是':'否','申诉状态':c.appeal?appealStatus(c.appeal.status):'','申诉理由':c.appeal?.reason||'','申诉提交人':c.appeal?.submitted_by||'','裁决人':c.appeal?.decided_by||'','裁决说明':c.appeal?.decision_note||'','标注是否修改/提交':changedStatus(c),'错误Case复盘':reviewCategory(c),'图片链接':Array.isArray(c.evidence)?c.evidence.join('\n'):''}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();ws['!cols']=[12,12,8,30,12,12,10,14,18,45,12,14,12,35,12,12,35,20,20,45].map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,'Case明细');XLSX.writeFile(wb,`R2V_Case明细_${day(new Date())}.xlsx`);showStatus(`已按当前筛选与质检表顺序导出 ${rows.length} 条Case明细。`);}
function appealStatus(s){return ({submitted:'申诉中',approved:'申诉成功',rejected:'申诉失败',withdrawn:'已撤回'})[s]||'待确认';}
function appealCaseDate(c){return day(c.case_date||c.feedback_date);}
function appealDisplayStatus(c){return c.appeal?appealStatus(c.appeal.status):'待申诉';}
function changedStatus(c){return c.changed===true?'已修改/提交':'待修改/提交';}
function reviewCategory(c){return String(c.raw_row?.reviewCategory||'');}
function ensureAppealInspectorColumn(){const table=document.querySelector('.appeal-table'),head=table?.querySelector('.column-headings'),filters=table?.querySelector('.column-filters');if(!head||!filters||$('appealInspectorFilter'))return;head.children[2].insertAdjacentHTML('afterend','<th>原始质检人</th>');filters.children[2].insertAdjacentHTML('afterend','<th><select id="appealInspectorFilter" aria-label="筛选原始质检人"><option value="all">全部</option></select></th>');}
function appealFilterBase(){return state.cases.filter(c=>c.kind==='quality'&&!c.invalid&&['P0','P1'].includes(c.severity)&&inPeriod(c.case_date||c.feedback_date));}
function populateAppealFilters(){const rows=appealFilterBase();setCaseFilterOptions('appealDateFilter',rows.map(c=>({value:appealCaseDate(c),label:appealCaseDate(c)})),'全部日期');setCaseFilterOptions('appealAnnotatorFilter',rows.map(c=>({value:c.annotator,label:c.annotator||'待匹配'})),'全部标注人');setCaseFilterOptions('appealInspectorFilter',rows.map(c=>({value:c.responsible_inspector,label:c.responsible_inspector||'待匹配'})),'全部原始质检人');setCaseFilterOptions('appealSeverityFilter',rows.map(c=>({value:c.severity,label:c.severity})),'全部等级');setCaseFilterOptions('appealReturnedFilter',rows.map(c=>({value:qualityReturned(c),label:qualityReturned(c)})),'全部打回状态');setCaseFilterOptions('appealSubmitterFilter',rows.map(c=>({value:c.appeal?.submitted_by||'—',label:c.appeal?.submitted_by||'—'})),'全部提交人');setCaseFilterOptions('appealStatusFilter',rows.map(c=>({value:appealDisplayStatus(c),label:appealDisplayStatus(c)})),'全部状态');setCaseFilterOptions('appealDeciderFilter',rows.map(c=>({value:c.appeal?.decided_by||'—',label:c.appeal?.decided_by||'—'})),'全部裁决人');setCaseFilterOptions('appealUpdatedFilter',rows.map(c=>({value:c.appeal?day(c.appeal.updated_at):'—',label:c.appeal?day(c.appeal.updated_at):'—'})),'全部更新时间');setCaseFilterOptions('appealChangedFilter',rows.map(c=>({value:changedStatus(c),label:changedStatus(c)})),'全部提交状态');setCaseFilterOptions('appealReviewFilter',rows.map(c=>({value:reviewCategory(c)||'未选择',label:reviewCategory(c)||'未选择'})),'全部复盘类型');}
function filteredAppeals(){const value=id=>$(id)?.value||'all',text=id=>($(id)?.value||'').trim().toLowerCase(),tid=text('appealTidFilter'),issue=text('appealIssueFilter'),reason=text('appealReasonFilter'),decision=text('appealDecisionFilter');let rows=appealFilterBase();const exact=[[value('appealDateFilter'),c=>appealCaseDate(c)],[value('appealAnnotatorFilter'),c=>c.annotator],[value('appealInspectorFilter'),c=>c.responsible_inspector],[value('appealSeverityFilter'),c=>c.severity],[value('appealReturnedFilter'),c=>qualityReturned(c)],[value('appealSubmitterFilter'),c=>c.appeal?.submitted_by||'—'],[value('appealStatusFilter'),c=>appealDisplayStatus(c)],[value('appealDeciderFilter'),c=>c.appeal?.decided_by||'—'],[value('appealUpdatedFilter'),c=>c.appeal?day(c.appeal.updated_at):'—'],[value('appealChangedFilter'),c=>changedStatus(c)],[value('appealReviewFilter'),c=>reviewCategory(c)||'未选择']];for(const [selected,getter] of exact)if(selected!=='all')rows=rows.filter(c=>getter(c)===selected);if(tid)rows=rows.filter(c=>String(c.tid||'').toLowerCase().includes(tid));if(issue)rows=rows.filter(c=>String(c.issue_detail||'').toLowerCase().includes(issue));if(reason)rows=rows.filter(c=>String(c.appeal?.reason||'').toLowerCase().includes(reason));if(decision)rows=rows.filter(c=>String(c.appeal?.decision_note||'').toLowerCase().includes(decision));return rows.sort(feedbackOrder);}
function renderAppeals(){populateAppealFilters();const eligible=filteredAppeals(),base=appealFilterBase(),pending=eligible.filter(c=>!c.appeal).length;$('appealFilterCount').textContent=`当前显示 ${eligible.length} 条，共 ${base.length} 条；其中待申诉 ${pending} 条，顺序与质检反馈 Excel 一致`;$('appealsTable').innerHTML=eligible.length?eligible.map(c=>`<tr><td>${esc(appealCaseDate(c))}</td><td>${esc(c.tid)}</td><td>${esc(c.annotator)}</td><td>${esc(c.responsible_inspector)}</td><td>${severityBadge(c.severity)}</td><td>${esc(qualityReturned(c))}</td><td title="${esc(c.issue_detail||'')}">${esc((c.issue_detail||'').slice(0,32))}</td><td title="${esc(c.appeal?.reason||'')}">${esc((c.appeal?.reason||'尚未提交').slice(0,32))}</td><td>${esc(c.appeal?.submitted_by||'—')}</td><td>${appealDisplayStatus(c)}</td><td>${esc(c.appeal?.decided_by||'—')}</td><td title="${esc(c.appeal?.decision_note||'')}">${esc((c.appeal?.decision_note||'—').slice(0,28))}</td><td>${esc(c.appeal?dateTime(c.appeal.updated_at):'—')}</td><td><select class="inline-table-select feedback-update" data-key="${esc(c.feedback_key)}" data-field="changed" aria-label="标注是否修改提交"><option value="false"${c.changed===true?'':' selected'}>待修改/提交</option><option value="true"${c.changed===true?' selected':''}>已修改/提交</option></select></td><td><select class="inline-table-select feedback-update" data-key="${esc(c.feedback_key)}" data-field="review" aria-label="错误Case复盘"><option value=""${reviewCategory(c)?'':' selected'}>未选择</option><option value="同 ID 判定错误"${reviewCategory(c)==='同 ID 判定错误'?' selected':''}>同 ID 判定错误</option><option value="ID 漏标"${reviewCategory(c)==='ID 漏标'?' selected':''}>ID 漏标</option><option value="参考图数量不足"${reviewCategory(c)==='参考图数量不足'?' selected':''}>参考图数量不足</option></select></td><td><button class="text-button case-open" data-key="${esc(c.feedback_key)}">${c.appeal?'查看':'申诉'}</button></td></tr>`).join(''):'<tr class="filter-empty"><td colspan="16" class="empty-cell">没有符合当前组合筛选条件的申诉 Case，可点击“清除筛选”恢复。</td></tr>';document.querySelectorAll('#appealsTable .case-open').forEach(b=>b.onclick=()=>openCase(b.dataset.key));document.querySelectorAll('#appealsTable .feedback-update').forEach(el=>el.onchange=()=>updateFeedbackTracking(el));}
function clearAppealFilters(){['appealDateFilter','appealAnnotatorFilter','appealInspectorFilter','appealSeverityFilter','appealReturnedFilter','appealSubmitterFilter','appealStatusFilter','appealDeciderFilter','appealUpdatedFilter','appealChangedFilter','appealReviewFilter'].forEach(id=>{if($(id))$(id).value='all'});['appealTidFilter','appealIssueFilter','appealReasonFilter','appealDecisionFilter'].forEach(id=>{if($(id))$(id).value=''});renderAppeals();}
function exportAppeals(){const rows=filteredAppeals();if(!rows.length)return showStatus('当前筛选条件下没有可导出的申诉记录。',true);const data=rows.map(c=>({'日期':appealCaseDate(c),'TID':c.tid,'标注人':c.annotator,'质检人':c.responsible_inspector,'错误等级':c.severity,'质检是否打回':qualityReturned(c),'质检意见':c.issue_detail||'','申诉理由':c.appeal?.reason||'','提交人':c.appeal?.submitted_by||'','申诉状态':appealDisplayStatus(c),'质检裁决人':c.appeal?.decided_by||'','裁决说明':c.appeal?.decision_note||'','更新时间':c.appeal?dateTime(c.appeal.updated_at):'','标注是否修改/提交':changedStatus(c),'错误Case复盘':reviewCategory(c)}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();ws['!cols']=[12,30,12,12,10,14,45,35,12,12,12,35,18,20,20].map(w=>({wch:w}));XLSX.utils.book_append_sheet(wb,ws,'申诉记录');XLSX.writeFile(wb,`R2V_申诉记录_${day(new Date())}.xlsx`);showStatus(`已按当前筛选与质检表顺序导出 ${rows.length} 条申诉记录。`);}
async function updateFeedbackTracking(el){const actor=await ensureActor();if(!actor)return renderAppeals();const f=state.feedback.find(x=>x.feedback_key===el.dataset.key);if(!f)return showStatus('未找到对应质检反馈记录。',true);el.classList.add('saving');const raw={...(f.raw_row||{}),trackingUpdatedBy:actor,trackingUpdatedAt:new Date().toISOString(),changedManagedOnline:true},payload={};if(el.dataset.field==='changed')payload.changed=el.value==='true';else raw.reviewCategory=el.value;payload.raw_row=raw;const {error}=await db.from('r2v_quality_feedback').update(payload).eq('feedback_key',f.feedback_key);el.classList.remove('saving');if(error){showStatus(`保存失败：${error.message}`,true);return renderAppeals();}Object.assign(f,payload);rebuild();renderCases();renderAppeals();showStatus(el.dataset.field==='changed'?'标注修改/提交状态已共享保存。':'错误 Case 复盘已共享保存。');}

function openCase(key){const c=state.cases.find(x=>x.feedback_key===key);if(!c)return;const events=sortedEvents(c.tid);const evidence=Array.isArray(c.evidence)?c.evidence:[];let action='';if(c.kind==='quality'&&!c.invalid&&['P0','P1'].includes(c.severity)){action=`<section class="drawer-section"><h3>申诉处理</h3>${c.appeal?`<p><strong>${appealStatus(c.appeal.status)}</strong></p><p>${esc(c.appeal.reason)}</p><p class="muted">${esc(c.appeal.decision_note||'')}</p><div class="appeal-actions"><button class="button small" data-decision="approved">判定成功</button> <button class="button small" data-decision="rejected">判定失败</button></div>`:`<form id="appealForm" class="appeal-form"><textarea name="reason" required placeholder="填写申诉理由与规则依据"></textarea><button class="button primary" type="submit">提交共享申诉</button></form>`}</section>`;}
  const appealTrail=c.appeal?`<section class="drawer-section"><h3>申诉流水</h3><div class="timeline"><div class="timeline-row"><time>${esc(dateTime(c.appeal.created_at))}</time><strong>提交申诉</strong><span>${esc(c.appeal.submitted_by)}：${esc(c.appeal.reason)}</span></div>${c.appeal.status!=='submitted'?`<div class="timeline-row"><time>${esc(dateTime(c.appeal.updated_at))}</time><strong>${appealStatus(c.appeal.status)}</strong><span>${esc(c.appeal.decided_by||'未记录裁决人')}：${esc(c.appeal.decision_note||'未填写裁决说明')}</span></div>`:''}</div></section>`:'';
  $('drawerContent').innerHTML=`<p class="eyebrow">${c.kind==='quality'?'QUALITY CASE':'ACCEPTANCE CASE'}</p><h2>${esc(c.tid)}</h2><section class="drawer-section"><div class="detail-grid"><div><span>标注责任人</span>${esc(c.annotator)}</div><div><span>质检责任人</span>${esc(c.responsible_inspector)}</div><div><span>反馈日期</span>${esc(day(c.feedback_date))}</div><div><span>错误等级</span>${c.kind==='quality'?severityBadge(c.severity):'验收不通过'}</div><div><span>问题类别</span>${esc(c.issue_category||'—')}</div><div><span>最终计错</span>${c.final_error?'是':'否'}</div></div></section><section class="drawer-section"><h3>反馈意见</h3><p>${esc(c.issue_detail||'暂无')}</p></section>${evidence.length?`<section class="drawer-section"><h3>质检截图</h3><div class="evidence-grid">${evidence.map(u=>`<a href="${esc(u)}" target="_blank" rel="noreferrer"><img src="${esc(u)}" alt="质检证据"></a>`).join('')}</div></section>`:''}${action}${appealTrail}<section class="drawer-section"><h3>完整流水</h3><div class="timeline">${events.map(e=>`<div class="timeline-row"><time>${esc(dateTime(e.event_time))}</time><strong>${esc(e.event_name)}</strong><span>${esc(normalizeName(e.operator_name)||e.reject_reason||'')}</span></div>`).join('')||'暂无匹配流水'}</div></section>`;
  $('caseDrawer').classList.add('open');$('caseDrawer').setAttribute('aria-hidden','false');$('drawerBackdrop').classList.remove('hidden');const form=$('appealForm');if(form)form.onsubmit=async e=>{e.preventDefault();await submitAppeal(c,form.reason.value)};document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>decideAppeal(c,b.dataset.decision));}
function closeDrawer(){$('caseDrawer').classList.remove('open');$('caseDrawer').setAttribute('aria-hidden','true');$('drawerBackdrop').classList.add('hidden');}
async function submitAppeal(c,reason){const actor=await ensureActor();if(!actor)return;const {error}=await db.from('r2v_quality_appeals').insert({feedback_key:c.feedback_key,tid:c.tid,reason,status:'submitted',submitted_by:actor});if(error)return showStatus(error.message,true);closeDrawer();await loadAll();showStatus('申诉已共享保存，准确率暂按错误显示，裁决成功后自动剔除。');}
async function decideAppeal(c,status){const actor=await ensureActor();if(!actor||!c.appeal)return;const note=prompt(status==='approved'?'填写申诉成功说明（可选）':'填写申诉失败说明（可选）','')??'';const {error}=await db.from('r2v_quality_appeals').update({status,decided_by:actor,decision_note:note}).eq('id',c.appeal.id);if(error)return showStatus(error.message,true);closeDrawer();await loadAll();showStatus(status==='approved'?'申诉成功，相关准确率已自动重新计算。':'申诉失败，错误继续计入准确率。');}

function renderImports(){$('importHistory').innerHTML=state.imports.length?state.imports.slice(0,30).map(i=>`<div class="history-row"><div><strong>${esc(i.file_name)}</strong><small> · ${esc(i.file_type)}</small></div><span>${i.row_count} 行</span><span>${esc(i.actor)} · ${esc(dateTime(i.created_at))}</span><button class="text-button import-delete" data-id="${esc(i.id)}">管理员删除</button></div>`).join(''):'<p class="empty-cell">暂无共享上传记录。</p>';$('adminAudit').innerHTML=state.adminAudit.length?state.adminAudit.slice(0,20).map(a=>`<div class="history-row"><div><strong>${a.action==='delete_import'?'删除上传记录':'修改管理员密码'}</strong><small>${esc(a.file_name||'')}</small></div><span>${esc(a.actor)}</span><span>${esc(dateTime(a.created_at))}</span></div>`).join(''):'<p class="empty-cell">暂无管理员操作记录。</p>';document.querySelectorAll('.import-delete').forEach(b=>b.onclick=()=>beginDelete(b.dataset.id));}
function beginDelete(id){const item=state.imports.find(i=>i.id===id);if(!item)return;state.pendingDelete=item;$('adminPanel').classList.remove('hidden');$('deleteConfirm').classList.remove('hidden');$('deleteFileName').textContent=`准备删除：${item.file_name}`;$('deletePin').value='';$('deletePin').focus();}
function cancelDelete(){state.pendingDelete=null;$('deleteConfirm').classList.add('hidden');$('deletePin').value='';}
async function deleteImport(){const item=state.pendingDelete,pin=$('deletePin').value,actor=await ensureActor();if(!item||!actor)return;if(!pin)return showStatus('请输入管理员密码。',true);$('confirmDelete').disabled=true;const {data,error}=await db.rpc('r2v_admin_delete_import',{p_import_id:item.id,p_pin:pin,p_actor:actor});$('confirmDelete').disabled=false;if(error)return showStatus(error.message,true);cancelDelete();await loadAll();showStatus(`已删除 ${data.file_name}，移除流水 ${data.events} 条、反馈 ${data.feedback} 条，准确率已重新计算。`);}
async function changeAdminPin(e){e.preventDefault();const form=e.currentTarget,actor=await ensureActor();if(!actor)return;const oldPin=form.oldPin.value,newPin=form.newPin.value;if(!/^\d{4,12}$/.test(newPin))return showStatus('新密码必须为4至12位数字。',true);const submit=form.querySelector('button[type="submit"]');submit.disabled=true;const {error}=await db.rpc('r2v_admin_change_pin',{p_old_pin:oldPin,p_new_pin:newPin,p_actor:actor});submit.disabled=false;if(error)return showStatus(error.message,true);form.reset();await loadAll();showStatus('管理员密码已修改，下次删除请使用新密码。');}
async function readCsv(file){const text=await file.text();const rows=parseCsv(text);if(rows.length<2)throw new Error('CSV没有有效数据');const h=rows[0],idx=n=>h.indexOf(n);return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>({tid:r[idx('TID')]||'',queue_id:r[idx('队列ID')]||'',queue_name:r[idx('队列名称')]||'',catalog_id:r[idx('目录ID')]||'',catalog_name:r[idx('目录名称')]||'',event_time:(r[idx('事件时间')]||'').replace(' ','T')+'+08:00',event_name:r[idx('事件')]||'',operator_uin:r[idx('操作人UIN')]||'',operator_name:r[idx('操作人姓名')]||'',reject_reason:r[idx('不通过原因')]||''}));}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q&&c==='"'&&n==='"'){cell+='"';i++;}else if(c==='"')q=!q;else if(!q&&c===','){row.push(cell);cell='';}else if(!q&&(c==='\n'||c==='\r')){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row)}if(rows[0]?.[0]?.charCodeAt(0)===0xfeff)rows[0][0]=rows[0][0].slice(1);return rows;}
function excelDate(v){if(v==null||v==='')return null;if(typeof v==='number'&&v>30000){const d=XLSX.SSF.parse_date_code(v);return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`;}const s=String(v).trim().replace(/[年/.]/g,'-').replace(/月/g,'-').replace(/日/g,'');const parts=s.split('-').filter(Boolean);if(parts.length===2)return `${new Date().getFullYear()}-${parts[0].padStart(2,'0')}-${parts[1].padStart(2,'0')}`;return s.slice(0,10);}
async function readFeedback(file){const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],arr=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});const h=arr[0].map(String),find=(...names)=>{for(const n of names){const i=h.findIndex(x=>x.trim()===n);if(i>=0)return i}return -1},idx={source:find('来源'),date:find('质检日期','反馈日期'),change:find('标注是否需要修改','质检是否打回'),movie:find('影片名'),tid:find('case id','Case ID','TID'),cat:find('问题类别'),detail:find('问题点','问题说明'),inspector:find('质检人'),changed:find('标注是否修改'),reply:11,recheck:find('是否建包质检'),severity:find('错误等级','等级','P级','P级别')};if(idx.change<0)idx.change=2;if(idx.tid<0)throw new Error('质检表未找到 case id 列');const rows=arr.slice(1).map((r,ri)=>{const tid=String(r[idx.tid]||'').trim();if(!tid)return null;const severity=String(r[idx.severity]||'').trim().toUpperCase().replace(/Ｐ/g,'P').replace(/０/g,'0').replace(/１/g,'1').replace(/２/g,'2').replace(/\s+/g,'')||'待定级',detail=String(r[idx.detail]||'').trim(),inspector=normalizeName(r[idx.inspector]),changeText=String(r[idx.change]||'').trim();const key=hashText([tid,excelDate(r[idx.date]),r[idx.cat],detail,inspector].join('|'));return {feedback_key:key,tid,feedback_date:excelDate(r[idx.date]),source:String(r[idx.source]||'').includes('验收')?'acceptance':'quality',severity:['P0','P1','P2','非人员责任'].includes(severity)?severity:'待定级',issue_category:String(r[idx.cat]||''),issue_detail:detail,inspector_name:inspector,movie_name:String(r[idx.movie]||''),needs_change:changeText==='是'?true:changeText==='否'?false:null,changed:String(r[idx.changed]||'')==='是',annotator_reply:String(r[idx.reply]||''),needs_recheck:String(r[idx.recheck]||'')==='是',evidence:[],raw_row:{excelRow:ri+2}}}).filter(Boolean);return {rows,data};}
async function extractAndUploadImages(data,rows){let zip;try{zip=await JSZip.loadAsync(data)}catch{return}const drawingNames=Object.keys(zip.files).filter(n=>/^xl\/drawings\/drawing\d+\.xml$/.test(n));for(const drawingName of drawingNames){const relName=drawingName.replace('xl/drawings/','xl/drawings/_rels/')+'.rels',relFile=zip.file(relName);if(!relFile)continue;const [drawingXml,relXml]=await Promise.all([zip.file(drawingName).async('text'),relFile.async('text')]),relDoc=new DOMParser().parseFromString(relXml,'text/xml'),relMap={};relDoc.querySelectorAll('Relationship').forEach(x=>relMap[x.getAttribute('Id')]=x.getAttribute('Target'));const doc=new DOMParser().parseFromString(drawingXml,'text/xml');for(const anchor of doc.querySelectorAll('twoCellAnchor,oneCellAnchor')){const rowNode=anchor.querySelector('from row'),blip=anchor.querySelector('blip');if(!rowNode||!blip)continue;const excelRow=Number(rowNode.textContent)+1,rid=blip.getAttribute('r:embed')||blip.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','embed'),target=relMap[rid];if(!target)continue;const mediaPath='xl/'+target.replace(/^\.\.\//,'').replace(/\\/g,'/'),media=zip.file(mediaPath);if(!media)continue;const row=rows.find(x=>x.raw_row.excelRow===excelRow);if(!row)continue;const blob=await media.async('blob');if(blob.size>20*1024*1024)continue;const ext=mediaPath.split('.').pop().toLowerCase(),mime=ext==='jpg'||ext==='jpeg'?'image/jpeg':`image/${ext}`,path=`feedback/${row.feedback_key}-${hashText(mediaPath)}.${ext}`;const {error}=await db.storage.from('r2v-quality-evidence').upload(path,new Blob([blob],{type:mime}),{upsert:true,contentType:mime});if(!error){const {data:url}=db.storage.from('r2v-quality-evidence').getPublicUrl(path);row.evidence.push(url.publicUrl);}}}}
async function createImport(file,type,count){const actor=await ensureActor();if(!actor)throw new Error('需要设置操作人姓名');const fp=hashText(`${file.name}|${file.size}|${file.lastModified}`);const query=()=>db.from('r2v_quality_imports').select('id').eq('file_type',type).eq('file_fingerprint',fp).maybeSingle();const {data:existing,error:lookupError}=await query();if(lookupError)throw lookupError;if(existing?.id)return existing.id;const {data,error}=await db.from('r2v_quality_imports').insert({file_name:file.name,file_type:type,file_fingerprint:fp,row_count:count,actor}).select('id').single();if(!error)return data.id;if(error.code==='23505'){const {data:duplicate,error:duplicateError}=await query();if(duplicateError)throw duplicateError;if(duplicate?.id)return duplicate.id;}throw error;}
async function saveEvents(file,type,channel){const rows=await readCsv(file),importId=await createImport(file,type,rows.length);const payload=dedupeBy(rows.map(r=>({...r,channel,import_id:importId,event_key:hashText([r.tid,r.event_time,r.event_name,r.operator_uin,r.queue_id].join('|'))})),'event_key');for(const part of chunk(payload,500)){const {error}=await db.from('r2v_quality_events').upsert(part,{onConflict:'event_key'});if(error)throw error;}return payload.length;}
async function fillMissingFeedbackDates(rows){const missing=rows.filter(r=>!r.feedback_date);if(!missing.length)return 0;const latestByTid=new Map(),tids=[...new Set(missing.map(r=>r.tid).filter(Boolean))];for(const part of chunk(tids,200)){const {data,error}=await db.from('r2v_quality_events').select('tid,event_time').eq('channel','quality').in('tid',part).order('event_time',{ascending:false});if(error)throw error;for(const e of data||[])if(!latestByTid.has(e.tid)&&day(e.event_time))latestByTid.set(e.tid,day(e.event_time));}const {data:latest,error:latestError}=await db.from('r2v_quality_events').select('event_time').eq('channel','quality').order('event_time',{ascending:false}).limit(1);if(latestError)throw latestError;const fallback=day(latest?.[0]?.event_time);let filled=0;for(const r of missing){const inferred=latestByTid.get(r.tid)||fallback;if(!inferred)continue;r.feedback_date=inferred;r.feedback_key=hashText([r.tid,r.feedback_date,r.issue_category,r.issue_detail,r.inspector_name].join('|'));filled++;}return filled;}
async function preserveOnlineFeedbackTracking(payload){const existing=new Map();for(const part of chunk(payload.map(r=>r.feedback_key),200)){const {data,error}=await db.from('r2v_quality_feedback').select('feedback_key,changed,raw_row').in('feedback_key',part);if(error)throw error;for(const row of data||[])existing.set(row.feedback_key,row);}for(const row of payload){const old=existing.get(row.feedback_key),raw=old?.raw_row||{};if(raw.changedManagedOnline)row.changed=old.changed;row.raw_row={...(row.raw_row||{}),...(raw.reviewCategory?{reviewCategory:raw.reviewCategory}:{}),...(raw.changedManagedOnline?{changedManagedOnline:true}:{}),...(raw.trackingUpdatedBy?{trackingUpdatedBy:raw.trackingUpdatedBy}:{}),...(raw.trackingUpdatedAt?{trackingUpdatedAt:raw.trackingUpdatedAt}:{})};}return payload;}
async function saveFeedback(file){const parsed=await readFeedback(file),rows=parsed.rows,filled=await fillMissingFeedbackDates(rows),importId=await createImport(file,'feedback',rows.length);showStatus(`正在提取 ${file.name} 中的质检截图…${filled?` 已按流水自动补齐 ${filled} 条日期。`:''}`);await extractAndUploadImages(parsed.data,rows);const payload=await preserveOnlineFeedbackTracking(dedupeBy(rows.map(r=>({...r,import_id:importId})),'feedback_key'));for(const part of chunk(payload,300)){const {error}=await db.from('r2v_quality_feedback').upsert(part,{onConflict:'feedback_key'});if(error)throw error;}return payload.length;}
async function importSelected(){const files=[['qualityFlowInput','quality_flow','quality'],['feedbackInput','feedback',''],['acceptanceFlowInput','acceptance_flow','acceptance']].map(x=>[$(x[0]).files[0],x[1],x[2]]).filter(x=>x[0]);if(!files.length)return showStatus('请至少选择一个文件。',true);$('importBtn').disabled=true;$('importBtn').textContent='正在解析并共享保存…';try{let total=0;for(const [file,type,channel] of files)total+=type==='feedback'?await saveFeedback(file):await saveEvents(file,type,channel);showStatus(`上传完成，共处理 ${total} 行。重复数据已自动更新，不会重复累计。`);await loadAll();}catch(e){showStatus(`上传失败：${e.message}`,true);}finally{$('importBtn').disabled=false;$('importBtn').textContent='解析并保存到共享看板';}}

function setView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`${view}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('pageTitle').textContent=titles[view];if(view==='cases')renderCases();if(view==='appeals')renderAppeals();}
function bindGo(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));}
ensureAppealInspectorColumn();
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('refreshBtn').onclick=loadAll;$('applyPeriodBtn').onclick=applyPeriod;$('periodSelect').onchange=setPeriodPreset;['startDate','endDate'].forEach(id=>{const el=$(id);el.onfocus=()=>{$('periodSelect').value='custom'};el.onchange=useCustomDates;});$('peopleSearch').oninput=e=>{const q=e.target.value.trim();document.querySelectorAll('#peopleTable tr').forEach(r=>r.hidden=q&&!r.textContent.includes(q));};['caseDateFilter','caseSourceFilter','caseAnnotatorFilter','caseInspectorFilter','caseSeverityFilter','caseReturnedFilter','caseCategoryFilter','caseStatusFilter'].forEach(id=>$(id).onchange=renderCases);['caseSearch','caseTidFilter','caseDetailFilter'].forEach(id=>$(id).oninput=renderCases);$('clearCaseFilters').onclick=clearCaseFilters;['appealDateFilter','appealAnnotatorFilter','appealInspectorFilter','appealSeverityFilter','appealReturnedFilter','appealSubmitterFilter','appealStatusFilter','appealDeciderFilter','appealUpdatedFilter','appealChangedFilter','appealReviewFilter'].forEach(id=>$(id).onchange=renderAppeals);['appealTidFilter','appealIssueFilter','appealReasonFilter','appealDecisionFilter'].forEach(id=>$(id).oninput=renderAppeals);$('clearAppealFilters').onclick=clearAppealFilters;$('closeDrawer').onclick=closeDrawer;$('drawerBackdrop').onclick=closeDrawer;$('identityBtn').onclick=()=>{state.actor='';ensureActor()};$('importBtn').onclick=importSelected;$('adminToggle').onclick=()=>{$('adminPanel').classList.toggle('hidden')};$('changePinForm').onsubmit=changeAdminPin;$('confirmDelete').onclick=deleteImport;$('cancelDelete').onclick=cancelDelete;['qualityFlowInput','feedbackInput','acceptanceFlowInput'].forEach(id=>$(id).onchange=e=>{e.target.closest('.upload-box').classList.toggle('selected',!!e.target.files[0]);$('selectedFiles').textContent=[...document.querySelectorAll('.upload-box input')].filter(x=>x.files[0]).map(x=>x.files[0].name).join('、')||'尚未选择文件';});
$('exportCasesBtn').onclick=exportCases;
$('exportAppealsBtn').onclick=exportAppeals;
syncPeriodDates();renderIdentity();loadAll();
