'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {createService,API}=require('./server.cjs');
const {snapshot}=require('./rules.cjs');

const uid=prefix=>`${prefix}_${randomUUID()}`;
async function main(){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'r2v-workbench-api-'));
 const groupPin='test-group-password',adminPin='test-admin-password';
 let service=createService({directory,groupPin,adminPin,allowedOrigins:['http://test.local']});
 await new Promise(resolve=>service.server.listen(0,'127.0.0.1',resolve));
 let base=`http://127.0.0.1:${service.server.address().port}${API}`;
 const proofs=[];
 async function request(endpoint,{token,body,method='GET',status=200,origin}={}){const response=await fetch(base+endpoint,{method,headers:{...(token?{'X-Workbench-Session':token}:{}),...(body?{'Content-Type':'application/json'}:{}),...(origin?{Origin:origin}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));return data;}
 async function login(profile,pin){return request('session',{method:'POST',body:{profile,pin}});}
 async function tx(session,delta,extras={}){const current=await request('state',{token:session.token});return request('transactions',{method:'POST',token:session.token,body:{id:randomUUID(),revision:current.revision,delta,...extras}});}
 async function failsTx(session,delta,{code,status=400,...extras}={}){const current=await request('state',{token:session.token});const before=JSON.stringify(current);const result=await request('transactions',{method:'POST',token:session.token,body:{id:randomUUID(),revision:current.revision,delta,...extras},status});if(code)assert.equal(result.error.code,code);assert.equal(JSON.stringify(await request('state',{token:session.token})),before);return result;}
 const profile=(name,role='annotation',groupId='g01',mode='single')=>({name,role,groupId,mode});
 await request('state',{status:401});
 await request('session',{method:'POST',body:{profile:profile('李甲','qc')},status:403});
 await request('session',{method:'POST',body:{profile:profile('李甲','acceptance'),pin:'wrong'},status:403});
 await request('session',{method:'POST',body:{profile:{name:'admin',role:'admin'},pin:'wrong'},status:403});
 await request('session',{method:'POST',body:{profile:profile('English')},status:400});
 await request('session',{method:'POST',body:{profile:profile('李甲')},origin:'https://other.test',status:403});
 const admin=await login({name:'admin',role:'admin'},adminPin),qc=await login(profile('组长','qc'),groupPin),acceptance=await login(profile('验收','acceptance'),groupPin),a=await login(profile('李甲')),b=await login(profile('李乙')),other=await login(profile('他组','qc','g02'),groupPin),multi=await login(profile('多组','qc','g06','multi'),groupPin);
 const blank=await request('state',{token:a.token});assert.equal(blank.revision,0);assert.equal(blank.state.tasks.length,0);assert.equal(blank.state.events.length,0);assert.equal(blank.state.version,3);assert(!JSON.stringify(blank).includes('DEMO'));
 proofs.push('正式库为空、无演示种子；会话令牌与角色 PIN、中文姓名、来源校验');
 const event=(task,type,fields={})=>({id:uid('event'),taskId:task.id,type,workflowVersion:3,actor:'伪造人',actorRole:'admin',at:'1900-01-01T00:00:00Z',...fields});
 function importDelta(tids,{groupId='g01',mode='single',movie='正式影片',date='2026-09-10'}={}){const batch={id:uid('batch'),groupId,mode,movie,date,createdAt:'1900-01-01',createdBy:'伪造人'};const tasks=tids.map(tid=>({id:uid('task'),tid,groupId,mode,movie,date,batchId:batch.id,createdAt:'1900-01-01',createdBy:'伪造人'}));batch.taskIds=tasks.map(t=>t.id);return{tasks,batches:[batch],events:tasks.map(t=>event(t,'dispatch',{note:'任务导入'}))};}
 const imported=importDelta(['TID-A','TID-B','TID-C','TID-D','TID-E']);await failsTx(a,imported,{status:403});await failsTx(other,imported,{status:403});const imp=await tx(admin,imported);const [ta,tb,tc,td,te]=imp.delta.tasks;
 assert(imp.delta.tasks.every(t=>t.createdBy==='admin'&&t.createdAt>'2026'));assert(imp.delta.events.every(e=>e.actor==='admin'&&e.actorRole==='admin'&&e.at>'2026'));
 await failsTx(qc,importDelta(['tid-a']),{status:409,code:'DUPLICATE_TID'});await failsTx(qc,importDelta(['TID-A'],{groupId:'g06',mode:'multi'}),{status:403});await failsTx(admin,importDelta(['tid-a'],{groupId:'g06',mode:'multi'}),{status:409});
 proofs.push('任务与导入批次原子保存；TID 全局大小写唯一；规范化服务器操作者与时间');
 const rev=imp.revision,bodyA={id:randomUUID(),revision:rev,delta:{events:[event(ta,'claim',{assignee:a.profile.name})]}},bodyB={id:randomUUID(),revision:rev,delta:{events:[event(ta,'claim',{assignee:b.profile.name})]}};
 const race=await Promise.all([fetch(base+'transactions',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Session':a.token},body:JSON.stringify(bodyA)}),fetch(base+'transactions',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Session':b.token},body:JSON.stringify(bodyB)})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);const won=race[0].status===200?a:b,lost=won===a?b:a,winningBody=won===a?bodyA:bodyB;const success=await race[won===a?0:1].json();assert.equal(snapshot((await request('state',{token:b.token})).state,ta.id).assignee,won.profile.name);
 const duplicate=await request('transactions',{method:'POST',token:won.token,body:winningBody});assert.deepEqual(duplicate,success);assert.equal((await request('state',{token:a.token})).revision,success.revision);
 await request('transactions',{method:'POST',token:won.token,body:{...winningBody,delta:{events:[event(tb,'claim')]}},status:409});await failsTx(lost,{events:[event(ta,'claim')]},{status:409});
 const beforeTwo=await request('state',{token:a.token});const bodyC={id:randomUUID(),revision:beforeTwo.revision,delta:{events:[event(tb,'claim')]}},bodyD={id:randomUUID(),revision:beforeTwo.revision,delta:{events:[event(tc,'claim')]}};await request('transactions',{method:'POST',token:a.token,body:bodyC});await request('transactions',{method:'POST',token:b.token,body:bodyD,status:409});await tx(b,bodyD.delta);
 proofs.push('双会话同任务竞态只一人成功；请求幂等与同 ID 不同内容拒绝；不同任务同步重试不丢更新');
 const complete=(task,round=1)=>({events:[event(task,'submit',{round})]});await failsTx(lost,complete(ta),{status:409});await tx(won,complete(ta));await failsTx(qc,{events:[event(ta,'qc_pass')]},{status:409});await failsTx(a,{events:[event(tb,'submit',{targetStatus:'accepted'})]});await failsTx(a,{events:[event(tb,'claim',{identityAlias:true,previousAssignee:'李甲',assignee:'他人'})]});
 async function pack(tasks,stage='qc',owner=qc){const current=(await request('state',{token:owner.token})).state;const views=tasks.map(t=>snapshot(current,t.id));const first=views[0],batch={id:uid('package'),kind:'handoff',groupId:first.groupId,mode:first.mode,movie:first.movie,date:first.date,packageName:'实际通航包',stage,taskIds:tasks.map(t=>t.id)};return{batches:[batch],events:views.flatMap(t=>{const common={packageId:batch.id,packageName:batch.packageName,stage,packageRound:t[stage==='qc'?'qcRound':'acceptanceRound']+1};return[event(t,'package_built',common),event(t,'package_claimed',common)];})};}
 let packaged=await pack([ta]);await failsTx(other,packaged,{status:403});await failsTx(qc,{...packaged,events:packaged.events.slice(0,1)});await tx(qc,packaged);
 await failsTx(qc,{events:[event(ta,'qc_fail',{pLevel:'P1',tags:[],note:'有问题'})]});await failsTx(qc,{events:[event(ta,'qc_pass',{qcRound:99})]},{status:409});await tx(qc,{events:[event(ta,'qc_fail',{pLevel:'P1',tags:['其他'],note:'需要修改'})]});
 const repairBefore=snapshot((await request('state',{token:a.token})).state,ta.id),rawTransfer=event(ta,'claim',{assignmentKind:'rework_transfer',fromAssignee:won.profile.name,assignee:lost.profile.name,assignmentStatus:'rework',note:'请假代修'});await failsTx(other,{events:[rawTransfer]},{status:403});await tx(qc,{events:[rawTransfer]});const repairAfter=snapshot((await request('state',{token:a.token})).state,ta.id);for(const key of ['status','round','qcRound','acceptanceRound','qcPackageId'])assert.equal(repairAfter[key],repairBefore[key]);assert.equal(repairAfter.assignee,lost.profile.name);await failsTx(won,complete(ta,2),{status:409});await tx(lost,complete(ta,2));await tx(qc,await pack([ta]));await tx(qc,{events:[event(ta,'qc_pass')]});await tx(qc,await pack([ta],'acceptance'));await tx(acceptance,{events:[event(ta,'acceptance_fail',{note:'验收问题'})]});
 proofs.push('强制先建包并领取再质检；错误等级/标签必填；组长请假代修只转归属、原记录和轮次保留');
 await failsTx(qc,{events:[event(ta,'claim',{assignmentKind:'rework_transfer',fromAssignee:lost.profile.name,assignee:won.profile.name,assignmentStatus:'acceptance_return_pending',note:'请假'})]},{status:409});await tx(qc,{events:[event(ta,'acceptance_route',{route:'qc',note:'质检处理'})]});await tx(qc,{events:[event(ta,'qc_repair_done',{note:'已修改'})]});await tx(qc,await pack([ta],'acceptance'));await tx(acceptance,{events:[event(ta,'acceptance_fail',{note:'标注需修改'})]});await tx(qc,{events:[event(ta,'acceptance_route',{route:'annotation',note:'退回标注'})]});await failsTx(acceptance,{events:[event(ta,'acceptance_pass')]},{status:409});await tx(lost,complete(ta,3));await tx(qc,await pack([ta]));await tx(qc,{events:[event(ta,'qc_pass')]});await tx(qc,await pack([ta],'acceptance'));await tx(acceptance,{events:[event(ta,'acceptance_pass')]});const end=snapshot((await request('state',{token:a.token})).state,ta.id);assert.equal(end.status,'accepted');assert.equal(end.round,3);assert.equal(end.qcRound,3);assert.equal(end.acceptanceRound,3);await failsTx(lost,complete(ta,4),{status:409});
 proofs.push('验收退回质检自行修改和退标注两路径；标注返修强制重过质检；终态禁止重复提交');
 await tx(a,{events:[event(tb,'annotator_reject',{note:'无法继续'})]});await failsTx(acceptance,{events:[event(tb,'acceptance_pass')]},{status:409});await tx(qc,{events:[event(tb,'reject_return',{resumeStatus:'accepted',note:'需要继续'})]});assert.equal(snapshot((await request('state',{token:a.token})).state,tb.id).status,'annotating');await tx(a,{events:[event(tb,'annotator_reject',{note:'确实无法继续'})]});await tx(qc,{events:[event(tb,'reject_confirm',{note:'确认拒绝'})]});assert.equal(snapshot((await request('state',{token:a.token})).state,tb.id).status,'rejected');
 const metadata=event(tc,'metadata_edit',{before:{tid:tc.tid,movie:tc.movie},after:{tid:'RENAMED-C',movie:'更正影片'},note:'导入更正'});await failsTx(qc,{events:[metadata]},{status:403});await failsTx(other,{events:[metadata]},{pin:adminPin,status:403});await tx(qc,{events:[metadata]},{pin:adminPin});const newState=(await request('state',{token:a.token})).state;assert.equal(newState.tasks.find(t=>t.id===tc.id).tid,'TID-C');assert.equal(snapshot(newState,tc.id).tid,'RENAMED-C');assert.equal(snapshot(newState,tc.id).assignee,b.profile.name);
 const daily={id:uid('group_day'),taskId:'group:g01',type:'group_daily_edit',groupId:'g01',mode:'single',date:'2026-09-10',before:{leader:'待填写',total:null,headcount:null},after:{leader:'组长',total:200,headcount:2.5},note:'每日登记'};await failsTx(qc,{events:[daily]},{status:403});await tx(qc,{events:[daily]},{pin:groupPin});await failsTx(qc,{events:[{...daily,id:uid('group_day')}]},{pin:groupPin,status:409});
 proofs.push('标注拒绝需质检再次确认；资料更正保留原任务；管理员/小组类别 PIN 验证与设置冲突阻止');
 const beforeAtomic=await request('state',{token:a.token});await failsTx(a,{events:[event(td,'claim'),event(tc,'claim')]},{status:409});assert.equal((await request('state',{token:a.token})).revision,beforeAtomic.revision);assert.equal(snapshot((await request('state',{token:a.token})).state,td.id).status,'unclaimed');
 const groupTwo=await tx(admin,importDelta(['GROUP-TWO'],{groupId:'g02'}));const t2=groupTwo.delta.tasks[0],a2=await login(profile('二组员','annotation','g02'));await tx(a2,{events:[event(t2,'claim'),event(t2,'submit',{round:1})]});await tx(other,await pack([t2],'qc',other));await tx(other,{events:[event(t2,'qc_pass')]});await tx(other,await pack([t2],'acceptance',other));await tx(acceptance,{events:[event(t2,'acceptance_pass')]});await failsTx(multi,{events:[event(td,'claim')]},{status:403});
 proofs.push('整批失败不落任何记录；验收本模块跨组正常；单多镜头权限隔离');
 const full=await request('state',{token:admin.token}),inc=await request('state?after=1',{token:admin.token});assert.equal(inc.revision,full.revision);assert.equal(inc.delta.tasks.length,full.state.tasks.length-5);const backup=await request('backup',{token:a.token});assert.deepEqual(backup.state,full.state);assert.equal(backup.transactions.length,full.revision);assert(!JSON.stringify(backup).includes(groupPin));assert(!JSON.stringify(backup).includes(adminPin));assert(!JSON.stringify(backup).includes(a.token));assert.throws(()=>service.db.prepare("DELETE FROM records WHERE id=?").run(ta.id),/append only/);
 const copy=path.join(directory,'verified-online-backup.sqlite');const saved=await service.onlineBackup(copy);assert.equal(saved.revision,full.revision);await service.rollingBackup();const backupCount=fs.readdirSync(path.join(directory,'backups')).length;assert.equal(backupCount,1);
 await service.close();service=createService({directory,groupPin,adminPin});await new Promise(resolve=>service.server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${service.server.address().port}${API}`;assert.deepEqual(await request('state',{token:a.token}),full);assert.deepEqual((await request('session',{token:qc.token})).profile,qc.profile);
 const restoreDir=path.join(directory,'isolated-restore');fs.mkdirSync(restoreDir);fs.copyFileSync(copy,path.join(restoreDir,'workbench.sqlite'));const restored=createService({directory:restoreDir,groupPin,adminPin});assert.deepEqual(restored.state(),full.state);assert.equal(restored.getRevision(),full.revision);await restored.close();await request('session',{method:'DELETE',token:a.token});await request('state',{token:a.token,status:401});
 proofs.push('增量与完整导出一致；审计不含 PIN/token；追加不可覆写；在线 SQLite 备份恢复与服务重启持久通过');
 await service.close();const result={ok:true,checkedAt:new Date().toISOString(),checks:proofs,revision:full.revision,tasks:full.state.tasks.length,events:full.state.events.length,batches:full.state.batches.length,temporaryDirectory:directory};if(process.env.RESULT_PATH)fs.writeFileSync(process.env.RESULT_PATH,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;setTimeout(()=>process.exit(1),20);});
